apiVersion: batch/v1
kind: Job
metadata:
  name: network-e2e-tests
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: network
          image: {{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}
          command: [
            "pytest",
            "tests",
            "-n", "auto",
            "--template=html1/index.html", "--report=report.html",
            "-m", {{ .Values.test.group | quote }}
          ]
      restartPolicy: Never
